language: node_js

node_js: 0.10

services:
  - mongodb

branches:
  only:
    - master

addons:
  hosts:
    - localhost

before_install:
  - sudo apt-get update && sudo apt-get install sendmail && sudo apt-get install elasticsearch

before_script:
  - npm install -g grunt-cli

after_success:
  - grunt coverage
